const states = [
    "Gujarat",
    "Maharashtra",
    "Goa",
    "Karnataka",
    "Kerala",
    "West Bengal",
    "Odisha",
    "Andhra Pradesh",
    "Tamil Nadu",
    "Pondicherry",
  ];
  
  const beachData = {
    Gujarat: [
      "Dumas Beach",
      "Suvali Beach",
      "Umbharat Beach",
      "Dandi Beach",
      "Dabhari Beach",
      "Diu Beach",
      "Tithal Beach",
      "Mandavi Beach",
      "Khambhat Beach",
    ],
    Maharashtra: [
      "Aksa Beach",
      "Alibaug Beach",
      "Gorai Beach",
      "Juhu Beach",
      "Manori Beach",
      "Marvé Beach",
      "Versova Beach",
      "Agardanda Beach",
      "Diveagar Beach",
      "Ganpatipule Beach",
      "Guhagar Beach",
      "Kelwa Beach",
      "Tarkarli Beach",
      "Shivaji Park Beach",
      "Anjarle Beach",
      "Dapoli Beach",
      "Dahanu Beach",
      "Srivardhan Beach",
      "Kihim Beach",
      "Mandwa Beach",
      "Velneshwar Beach",
      "Vengurla Beach",
      "Bassein Beach",
      "Bhandarpule Beach",
      "Nagaon Beach",
      "Revdanda Beach",
      "Rewas Beach",
      "Kashid Beach",
      "Karde (Murud) Beach",
      "Harihareshwar Beach",
      "Bagmandla Beach",
      "Kelshi Beach",
      "Harnai Beach",
      "Bordi Beach",
      "Ratnagiri Beach",
      "Awas Beach",
      "Sasawne Beach",
      "Malvan Beach",
    ],
    Goa: [
      "Palolem Beach",
      "Agonda Beach",
      "Arambol Beach",
      "Benaulim Beach",
      "Cavelossim Beach",
      "Chapora Beach",
      "Mandrem Beach",
      "Varca Beach",
      "Baga Beach",
      "Candolim Beach",
      "Calangute Beach",
      "Colva Beach",
    ],
    Karnataka: [
      "Karwar Beach",
      "Kudle Beach",
      "Panambur Beach",
      "NITK Beach",
      "Sasihithlu Beach",
      "Maravanthe Beach",
      "Tannirubhavi Beach",
      "Malpe Beach",
      "Murudeshwara Beach",
      "Apsarakonda Beach",
      "Om Beach",
      "Kaup Beach",
      "Kodi Beach",
      "Someshwar Beach",
      "St Mary's Island Beach",
      "Mukka Beach",
      "Ullal Beach",
    ],
    Kerala: [
      "Kollam Beach",
      "Cherai Beach",
      "Chavakkad Beach",
      "Fort Kochi Beach",
      "Kanhangad Beach",
      "Marari Beach",
      "Meenkunnu Beach",
      "Muzhappilangad Beach",
      "Payyambalam Beach",
      "Shangumughom Beach",
      "Snehatheeram Beach",
      "Kappil Beach",
      "Thirumullavaram Beach",
      "Hawa Beach",
      "Samudra Beach",
      "Lighthouse Beach",
      "Kannur Beach",
      "Kappad Beach",
      "Varkala Beach",
    ],
    "West Bengal": [
      "Henry Island Beach",
      "Bakkhali Sea Beach",
      "Frasergunj Sea Beach",
      "Gangasagar Sea Beach",
      "Junput Beach",
      "Bankiput Sea Beach",
      "Mandarmani Beach",
      "Shankarpur Beach",
      "Tajpur Beach",
      "Digha Sea Beach",
      "Udaypur Sea Beach",
    ],
    Odisha: [
      "Talsari Beach",
      "Dagara Beach",
      "Chandipur Beach",
      "Gahirmatha Beach",
      "Satabhaya Beach",
      "Pentha Sea Beach",
      "Hukitola Beach",
      "Paradeep Beach",
      "Astaranga Beach",
      "Beleswar Beach",
      "Konark Beach",
      "Chandrabhaga Beach",
      "Ramachandi Beach",
      "Puri Beach",
    ],
    "Andhra Pradesh": [
      "Rushikonda Beach",
      "Bheemili Beach",
      "Mypadu Beach",
      "Suryalanka Beach",
      "Ramakrishna Beach",
      "Manginapudi Beach",
      "Vodarevu Beach",
      "Kothapatnam Beach",
      "Yanam Beach",
    ],
    "Tamil Nadu": [
      "Marina Beach",
      "Elliot's Beach",
      "Kasimedu Beach",
      "Golden Beach",
      "Mahabalipuram Beach",
      "Kanyakumari Beach",
      "Dhanushkodi Beach",
      "Velankanni Beach",
    ],
    Pondicherry: [
      "Promenade Beach",
      "Karaikal Beach",
      "Auroville Beach",
      "Paradise Beach",
      "Serenity Beach",
    ],
  };